
modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "undergroundfire"
version = "1.0"
displayName = "Underground Fire"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "undergroundfire.png"
credits = ""
authors = "XuFly"
description ='''
'''

[[dependencies.undergroundfire]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.undergroundfire]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
